### ISSUE TITLE
Support documentation generation based on MkDocs

### ISSUE THREAD

**Issue by msclock** [serious-scaffold/ss-cpp#318]

**Comment by huxuan** [comment]
Actually, I have very very **personal** preference that sphinx + myst + furo should be enough. One of the most important reason I do not prefer mkdocs because there are many [paied features](https://squidfunk.github.io/mkdocs-material/insiders/) in mkdocs-material (not mkdocs itself). So when using mkdocs, the user may suffer on either not using the most popular material theme or can not use some features without payment.

**Comment by msclock** [comment]
> there are many [paied features](https://squidfunk.github.io/mkdocs-material/insiders/) in mkdocs-material and its plugins (not mkdocs itself)

Yep, but it is still popular in the opensource community. 

> the user may suffer on either not using the most popular material theme or can not use some features without payment.

Actually plugins and features are all trade off choice I think. There're still awesome plugins apart from the most popular material theme.

@huxuan I just consider the two are the most document generator so let's have one more option.

**Comment by huxuan** [comment]
> I just consider the two are the most document generators so let's have one more option.

It is totally OK. I am not against this. Just express some my personal ideas. It just means I will not pay special efforts to apply this.
